version: '3.1'

services:
  client:
    container_name: cftools-discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./config/config.js:/app/config/config.js:ro
      - ./config/servers.js:/app/config/servers.js:ro
      - ./cftools-discord-bot.db:/app/cftools-discord-bot.db
    env_file:
      - config/.env
